import axios from "axios"

const products = [
    {
      "name": "Lait demi-écremé",
      "stock": 200,
      "price": "20",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/lait.jpg",
      "reference": '1',
      "category": '1',
    },
    {
      "name": "yaourt",
      "stock": 201,
      "price": "11",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/yaourt.jpg",
      "reference": '2',
      "category": '1',
    },
    {
      "name": "creme fraiche",
      "stock": 202,
      "price": "24.5",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/creme.jpg",
      "reference": '3',
      "category": '1',
    },
    {
      "name": "raclette",
      "stock": 203,
      "price": "34.99",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/FROMAGE.jpg",
      "reference": '4',
      "category": '1',
    },
    {
      "name": "beurre",
      "stock": 204,
      "price": "37",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/beuure.jpg",
      "reference": '5',
      "category": '1',
    },
    {
      "name": "viande haché",
      "stock": 205,
      "price": "43",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/viandes-haches.jpg",
      "reference": '6',
      "category": '2',
    },
    {
      "name": "poulet ",
      "stock": 206,
      "price": "49",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/poulet.jpg",
      "reference": '7',
      "category": '2',
    },
    {
      "name": "merguez",
      "stock": 207,
      "price": "54",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/merguez.jpg",
      "reference": '8',
      "category": '2',
    },
    {
      "name": "dinde farci",
      "stock": 208,
      "price": "60",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/dinde2.jpg",
      "reference": '9',
      "category": '2',
    },
    {
      "name": "bacon de dinde",
      "stock": 209,
      "price": "66",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/dinde.jpg",
      "reference": '10',
      "category": '2',
    },
    {
      "name": "tomates",
      "stock": 210,
      "price": "72",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/tomates.jpg",
      "reference": '11',
      "category": '3',
    },
    {
      "name": "kiwi",
      "stock": 211,
      "price": "78",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/kiwi.jpg",
      "reference": '12',
      "category": '3',
    },
    {
      "name": "brocoli",
      "stock": 212,
      "price": "83",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/brocoli.jpg",
      "reference": '13',
      "category": '3',
    },
    {
      "name": "banane",
      "stock": 213,
      "price": "89",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/banane.jpg",
      "reference": '14',
      "category": '3',
    },
    {
      "name": "riz",
      "stock": 214,
      "price": "95",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/riz.jpg",
      "reference": '15',
      "category": '4',
    },
    {
      "name": "pates",
      "stock": 215,
      "price": "101",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/pates.jpg",
      "reference": '16',
      "category": '4',
    },
    {
      "name": "haricot verts",
      "stock": 216,
      "price": "107",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/conserve.jpg",
      "reference": '17',
      "category": '3',
    },
    {
      "name": "cacahuetes",
      "stock": 217,
      "price": "112",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/cacahuetes.jpg",
      "reference": '18',
      "category": '4',
    },
    {
      "name": "chips",
      "stock": 218,
      "price": "118",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/chips.jpg",
      "reference": '19',
      "category": '4',
    },
    {
      "name": "snikers",
      "stock": 219,
      "price": "124",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/snikers.jpg",
      "reference": '20',
      "category": '5',
    },
    {
      "name": "cereales",
      "stock": 220,
      "price": "130",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/cereales.jpg",
      "reference": '21',
      "category": '5',
    },
    {
      "name": "chocolat",
      "stock": 221,
      "price": "136",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/chocolat.jpg",
      "reference": '22',
      "category": '5',
    },
    {
      "name": "cookies",
      "stock": 222,
      "price": "141",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/cookies.jpg",
      "reference": '23',
      "category": '5',
    },
    {
      "name": "creme glacé vanille",
      "stock": 223,
      "price": "147",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/glace.jpg",
      "reference": '24',
      "category": '5',
    },
    {
      "name": "cone glace extreme",
      "stock": 224,
      "price": "153",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/glace2.jpg",
      "reference": '25',
      "category": '5',
    },
    {
      "name": "fruit rouge melange",
      "stock": 225,
      "price": "159",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/fruit-rouge.jpg",
      "reference": '26',
      "category": '6',
    },
    {
      "name": "couscous",
      "stock": 226,
      "price": "165",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/couscous-surgele.jpg",
      "reference": '27',
      "category": '6',
    },
    {
      "name": "nuggets",
      "stock": 227,
      "price": "170",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/nuggets.jpg",
      "reference": '28',
      "category": '6',
    },
    {
      "name": "oasis",
      "stock": 228,
      "price": "176",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/oasis.jpg",
      "reference": '29',
      "category": '7',
    },
    {
      "name": "lipton",
      "stock": 229,
      "price": "182",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/lipton.jpg",
      "reference": '30',
      "category": '7',
    },
    {
      "name": "eau",
      "stock": 230,
      "price": "188",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/eau.jpg",
      "reference": '31',
      "category": '7',
    },
    {
      "name": "fruit shoot",
      "stock": 231,
      "price": "194",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/fruitshoot.jpg",
      "reference": '32',
      "category": '7',
    },
    {
      "name": "monster",
      "stock": 232,
      "price": "199",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/monster.jpg",
      "reference": '33',
      "category": '7',
    },
    {
      "name": "gel",
      "stock": 233,
      "price": "205",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/gel.jpg",
      "reference": '34',
      "category": '8',
    },
    {
      "name": "dentifrice",
      "stock": 234,
      "price": "211",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/dentifrice.jpg",
      "reference": '35',
      "category": '8',
    },
    {
      "name": "rasoir",
      "stock": 235,
      "price": "217",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/rasoir.jpg",
      "reference": '36',
      "category": '8',
    },
    {
      "name": "shampoing",
      "stock": 236,
      "price": "222",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/shampoing.jpg",
      "reference": '37',
      "category": '8',
    },
    {
      "name": "lait corps hydratant",
      "stock": 237,
      "price": "228",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/creme-corps.jpg",
      "reference": '38',
      "category": '8',
    },
    {
      "name": "balai serpillere",
      "stock": 238,
      "price": "238",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/balai.jpg",
      "reference": '39',
      "category": '9',
    },
    {
      "name": "nettoyant vitre",
      "stock": 239,
      "price": "240",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/netooyant.jpg",
      "reference": '40',
      "category": '9',
    },
    {
      "name": "liquide vaisselle",
      "stock": 240,
      "price": "246",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/liquide-vaisselle.jpg",
      "reference": '41',
      "category": '9',
    },
    {
      "name": "eponge",
      "stock": 241,
      "price": "251",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/eponge.jpg",
      "reference": '42',
      "category": '9',
    },
    {
      "name": "anti volant, mouche, moustique ",
      "stock": 242,
      "price": "257",
      "Image": "http://projets.local/api-wp/wp-content/uploads/2023/05/insecticide.jpg",
      "reference": '43',
      "category": '9',
    }
   ]


   products.map(prod => {

    axios.post('http://localhost:1337/api/products', {
      data: {
        name: prod.name,
        stock: prod.stock,
        price: prod.price,
        image: prod.Image,
        reference: prod.reference,
      }
    }).then(res => {
      const id = res.data.data.id
      axios.put(`http://localhost:1337/api/products/${id}`, {
        data: {
          category: {
            set: [prod.category]
          }
        }
      })
    })

   })

